site_name: Elemental Craft Wiki
nav:
- Home: 'index.md'
- Sources: 'sources.md'
- Blocks:
  - Inert Crystal Ore: 'blocks/inert-crystal-ore.md'
  - Pipes: 'blocks/pipes.md'
  - Shrines:
    - Shrines: 'blocks/shrines/index.md'
    - Ore Shrine: 'blocks/shrines/ore-shrine.md'
- Items:
  - Element Shards: 'items/shards.md'
  - Source Stabilizer: 'items/source-stabilizer.md'
  - Source Receptacle: 'items/source-receptacle.md'
- Tool Infusions: 'tool-infusions.md'

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

repo_name: Sirttas/ElementalCraft
repo_url: https://github.com/Sirttas/ElementalCraft
edit_uri: https://github.com/Sirttas/ElementalCraftDoc/edit/main/docs/